#!/bin/bash
echo "Building Project: SpringBoard...."
doSync SpringBoard $*
echo "Building Project: TurnHandle...."
doSync TurnHandle $*
echo "Building Project: BassBot...."
doSync BassBot $*
echo "Building Project: BassBotSlave...."
doSync BassBotSlave $*
echo "Building Project: Kalimba...."
doSync Kalimba $*
echo "Building Project: BatkTest...."
doSync BatkTest $*
echo "done..."