#!/bin/bash
echo "Syncing Batk library to sysroot...."
rsync -ac --out-format="   %n" --no-t --delete-after ${XC_ROOT}/Bela/libraries/Batk/ ${XC_ROOT}/sysroot/root/Bela/libraries/Batk/ 
echo "Building Project: SpringBoard...."
make -j8 PROJECT=SpringBoard
echo "Building Project: TurnHandle...."
make -j8 PROJECT=TurnHandle
echo "Building Project: BassBot...."
make -j8 PROJECT=BassBot
echo "Building Project: BassBotSlave...."
make -j8 PROJECT=BassBotSlave
echo "Building Project: Kalimba...."
make -j8 PROJECT=Kalimba
echo "Building Project: BatkTest...."
make -j8 PROJECT=BatkTest
echo "done..."