#!/bin/bash
if [ $# -eq 0 ]; then
    echo "No arguments supplied"
    exit -1
fi

PROJECT_NAME=$1
shift

PROJECT_FOLDER=${XC_ROOT}/Bela/projects
PROJECT_DIR=$PROJECT_FOLDER/$PROJECT_NAME
if [ -d "$PROJECT_DIR" ]; then
  ### Take action if $PROJECT_DIR exists ###
  echo "Project Found in ${PROJECT_DIR}..."
else
  ###  Control will jump here if $PROJECT_DIR does NOT exists ###
  echo "Error: Project $PROJECT_NAME not found...... available projects:"
  ls "$PROJECT_FOLDER" -1
  echo "------------------------------------------------------------"
  exit 1
fi


SYNC_SAMPLES=0
CLEAN=0
RUN_PROJECT=1
RUN_MODE=foreground
FETCH_PRESETS=0
SYNC_PRESETS=0
BUILD_PROJECT=1
SYNC_PROJECT=1
CONNECT=1

while [ -n "$1" ]
do
	case $1 in
		-b)
			RUN_MODE=screen;
		;;
		-f)
			RUN_MODE=foreground;
		;;
		-s)
			RUN_MODE=screenfg;
		;;
		-n)
			RUN_MODE=none;
			RUN_PROJECT=0;
		;;
		-ns)
			SYNC_PROJECT=0;
		;;
		-nb)
			BUILD_PROJECT=0;
		;;
		-nc)
			CONNECT=0;
		;;
		--clean)
			CLEAN=1;
		;;
		--cleanall)
			CLEAN=2;
		;;
		--samples)
			SYNC_SAMPLES=1;
		;;
		--ip)
			shift
			XC_IP=$1;
		;;
		--fetch-presets)
			FETCH_PRESETS=1;
		;;
		--sync-presets)
			SYNC_PRESETS=1;
		;;
	esac
	shift
done

BASEDIR=$(dirname "$0")
export XC_IP=${XC_IP:=192.168.6.2}
export XC_ROOT=${XC_ROOT:="`realpath $BASEDIR/..`"}
export XC_CL_OPTS=${XC_CL_OPTS:="-X 0"}
export XC_USER=${XC_USER:=root}
export XC_SSH=${XC_USER}@${XC_IP}


xcExec() {
    ssh -o LogLevel=ERROR $XC_SSH "$*"
}

#echo "Project: $PROJECT_NAME"

if [ $FETCH_PRESETS == 1 ]; then 
	echo "Fetching Presets from project: $PROJECT_NAME on $XC_SSH...."
	rsync -ac --out-format="   %n" --no-t $XC_SSH:Bela/projects/$PROJECT_NAME/Presets/ ${XC_ROOT}/Bela/projects/$PROJECT_NAME/Presets/  
	exit 1
fi

if [ $BUILD_PROJECT == 1 ]; then 
	echo "Building before synching...."
	if [ $CLEAN == 2 ]; then
		echo "Cleaning All...."
		make cleanall
	elif [ $CLEAN == 1 ]; then
		echo "Cleaning Project $PROJECT_NAME...."
		make clean PROJECT=$PROJECT_NAME
	fi
	echo "Syncing Batk library to sysroot...."
	rsync -ac --out-format="   %n" --no-t --delete-after ${XC_ROOT}/Bela/libraries/Batk/ ${XC_ROOT}/sysroot/root/Bela/libraries/Batk/ #trailing slashes used here make sure rsync does not create another folder inside the target folder
	echo "Building Project: $PROJECT_NAME...."
	make -j8 PROJECT=$PROJECT_NAME
	echo "Build done..."
fi

if [ $CONNECT == 1 ]; then
	ping -c 1 -t 1 $XC_IP >/dev/null 2>&1 
	if [ $? -ne 0 ]; then
	    echo WARNING: unable to connect to ${XC_IP}, check XC_IP?
	    exit -1
	fi
else
	exit 1
fi

if [ $SYNC_PROJECT == 1 ]; then
	echo "Syncing Library: Batk to $XC_SSH...."
	rsync -ac --out-format="   %n" --no-t --delete-after --exclude=build --exclude=Makefile.inc ${XC_ROOT}/Bela/libraries/Batk/ $XC_SSH:Bela/libraries/Batk/  
	rsync -ac --out-format="   %n" --no-t --delete-after ${XC_ROOT}/build/sysroot/root/Bela/libraries/Batk/ $XC_SSH:Bela/libraries/Batk/build/  
	echo "Syncing Project: $PROJECT_NAME to $XC_SSH...."
	rsync -ac --out-format="   %n" --no-t --delete-after --exclude=Presets --exclude=$PROJECT_NAME --exclude=build ${PROJECT_DIR}/ $XC_SSH:Bela/projects/$PROJECT_NAME/  
	rsync -ac --out-format="   %n" --no-t --delete-after --exclude=Makefile.inc ${XC_ROOT}/build/Bela/projects/$PROJECT_NAME/ $XC_SSH:Bela/projects/$PROJECT_NAME/build/  
	rsync -ac --out-format="   %n" --no-t ${XC_ROOT}/build/$PROJECT_NAME $XC_SSH:Bela/projects/$PROJECT_NAME/
fi

if [ $SYNC_SAMPLES == 1 ]; then
	echo "Syncing Samples library to $XC_SSH...."
	rsync -ac --out-format="   %n" --no-t --delete-after ${XC_ROOT}/../samples/ $XC_SSH:Bela/samples/
fi

if [ $SYNC_PRESETS == 1 ]; then 	
	PROJECT_DIR=${XC_ROOT}/Bela/projects/$PROJECT_NAME/Presets
	if [ -d "$PROJECT_DIR" ]; then
		echo "Syncing Presets to $XC_SSH:Bela/project/$PROJECT_NAME/Presets"
		rsync -ac --out-format="   %n" --no-t ${XC_ROOT}/Bela/projects/$PROJECT_NAME/Presets/ $XC_SSH:Bela/projects/$PROJECT_NAME/Presets/
	else
		###  Control will jump here if $PROJECT_DIR does NOT exists ###
		echo "--sync-presets: ${PROJECT_DIR} not found."
	fi
fi

if [ $RUN_PROJECT == 1 ]; then
	echo "Running Project: $PROJECT_NAME on $XC_SSH...."
	MAKE_COMMAND="make QUIET=true --no-print-directory -C ~/Bela PROJECT='$PROJECT_NAME' CL='$XC_CL_OPTS'"
	case $RUN_MODE in
		# Sorry for repeating the options, but "ssh / ssh -t" makes things complicated
		foreground)
			ssh -t $XC_SSH "$MAKE_COMMAND run" || exit 1
		;;
		screen)
			ssh $XC_SSH "$MAKE_COMMAND runscreen"
		;;
		screenfg)
			ssh -t $XC_SSH "$MAKE_COMMAND runscreenfg"
		;;
	esac
fi
