#!/bin/bash
echo "Deploying SpringBoard...."
doSync SpringBoard -b --ip 192.168.0.110 --sync-samples --clean-remote -c "-p64" "$*"
echo "done..."
echo "Deploying TurnHandle...."
doSync TurnHandle -b --ip 192.168.0.111 --sync-samples  --clean-remote -c "-p64" "$*"
echo "done..."
echo "Deploying BassBot...."
doSync BassBot -b --ip 192.168.0.112  --clean-remote -c "-p64" "$*"
echo "done..."
echo "Deploying BassBotSlave...."
doSync BassBotSlave -b --ip 192.168.0.113  --clean-remote -c "-p64" "$*"
echo "done..." 

