#!/bin/bash
echo "Deploying SpringBoard...."
doSync SpringBoard -b --sync-samples --clean-remote -c "-p64" "$*"
echo "done..."
echo "Deploying TurnHandle...."
doSync TurnHandle -b --sync-samples  --clean-remote -c "-p64" "$*"
echo "done..."
echo "Deploying BassBot...."
doSync BassBot -b --clean-remote -c "-p64" "$*"
echo "done..."
echo "Deploying BassBotSlave...."
doSync BassBotSlave -b --clean-remote -c "-p64" "$*"
echo "done..." 

